spring:
  datasource:
    url: 'jdbc:oracle:thin:@localhost:1521/orclpdb'
    username: 'SENA_OWNER'
    password: 'junu'
    driverClassName: 'oracle.jdbc.OracleDriver'
    platform: 'oracle'
  jpa:
    database-platform: 'org.hibernate.dialect.Oracle12cDialect'
    show-sql: true
    generate-ddl: false
    hibernate.ddl-auto: validate
